workflows:
  ios-build:
    name: Build iOS WebView
    instance_type: mac_mini_m2
    max_build_duration: 60
    scripts:
      - name: Build iOS app
        script: xcode-project build-ipa --scheme ios-webview-app --project ios-webview.xcodeproj
    artifacts:
      - build/ios/ipa/*.ipa