workflows:
  ios-build:
    name: Build iOS WebView
    instance_type: mac_mini_m2
    max_build_duration: 60
    scripts:
      - name: Build iOS app
        script: xcode-project build-ipa --project ios-webview/webview.xcodeproj --scheme ios-webview
    artifacts:
      - build/ios/ipa/*.ipa
